### ISSUE TITLE
No matching distribution found for torch==2.3.1+cu121

### ISSUE THREAD

**Issue by RoyDingZF** [wusongbai139/controlnet_train_webUI#1]
ERROR: Could not find a version that satisfies the requirement torch==2.3.1+cu121 (from versions: 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.4.0)
ERROR: No matching distribution found for torch==2.3.1+cu121

**Comment by RoyDingZF** [comment]
also this line in requirements.txt:
flash_attn @ file:///H:/AIGC/models/captions/Florence_2_large/

**Comment by wusongbai139** [comment]
Installation of flash-attention
    1. Method (I):
        - cd your project file root directory
        - ```git clone https://github.com/Dao-AILab/flash-attention.git```
        - cd flash-attention
        - python setup.py install
    2. Method (II):
        - Go to: https://github.com/Dao-AILab/flash-attention/releases
        - Select the appropriate version in Assets, download and put it in your project folder
        - Execute: ```pip install flash_attn-2.6.3+cu118torch2.cxx11abiTRUE-cp311-cp311-linux_x86_64.whl```
